### ISSUE TITLE
When running weather getting config_current is not defined

### ISSUE THREAD

**Issue by gjm19761** [liam8888999/ErsatzTV-Filler#232]
**Describe the bug**
Weather Generation not working

getting this error ;

2024-12-03 12:13:06 | info: starting weather
2024-12-03 12:13:06 | error: Error encountered in Weather: ReferenceError: config_current is not defined | Error

however there is no setting anywhere called config_current?

**Comment by liam8888999** [comment]
this is getting a fix pushed for it right now :)

**Comment by liam8888999** [comment]
Forgot to mention, config_current is an internal variable that reads whatever is in the config file rather than something you can change if you were looking for somewhere to change/set it

**Comment by gjm19761** [comment]
now getting these errors since updating...
2024-12-03 17:37:26 | info: running weather function from run api
2024-12-03 17:37:26 | warn: Directory already exists, will not be created: D:\ersatzfiller\workdir\Weather
2024-12-03 17:37:26 | info: starting weather
2024-12-03 17:37:26 | success: Found the user selected theme file... loading...
2024-12-03 17:37:26 | debug: Current Theme json: [object Object]
2024-12-03 17:37:26 | debug: Hwaccell: no hwaccel
2024-12-03 17:37:26 | debug: Hwaccell_device: no hwacceldevice
2024-12-03 17:37:26 | debug: Weather video fade out start: 10
2024-12-03 17:37:26 | debug: Weather Audio Fade out start: 10
2024-12-03 17:37:26 | info: ass file path: D:\ersatzfiller\workdir\Weather\error.ass
2024-12-03 17:37:26 | info: ass location substituted: D\:/ersatzfiller/workdir/Weather/error.ass
2024-12-03 17:37:26 | info: Downloading weather images
2024-12-03 17:37:26 | info: Current City: Marlborough
2024-12-03 17:37:26 | info: Weatherdir: D:\ersatzfiller\workdir\Weather
2024-12-03 17:37:26 | success: D:\ersatzfiller\workdir\Weather\v1.png
2024-12-03 17:37:27 | success: D:\ersatzfiller\workdir\Weather\v2.png
2024-12-03 17:37:27 | success: D:\ersatzfiller\workdir\Weather\v3.png
2024-12-03 17:37:27 | error: Failed to download with status code 404 | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14)
    at ClientRequest.<anonymous> (C:\snapshot\ErsatzTV-Filler\server\utils\downloadimage.utils.js:27:16)
    at Object.onceWrapper (node:events:652:26)
    at ClientRequest.emit (node:events:537:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:642:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:505:22)
2024-12-03 17:37:27 | error: Failed to download with status code 404 | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async downloadimages (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:101:5)
    at async WEATHER (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:299:7)
    at async C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:37:3
2024-12-03 17:37:27 | error: Failed to download with status code 404 | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14)
    at ClientRequest.<anonymous> (C:\snapshot\ErsatzTV-Filler\server\utils\downloadimage.utils.js:27:16)
    at Object.onceWrapper (node:events:652:26)
    at ClientRequest.emit (node:events:537:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:642:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:505:22)
2024-12-03 17:37:27 | error: Failed to download with status code 404 | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async downloadimages (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:105:7)
    at async WEATHER (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:299:7)
    at async C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:37:3
2024-12-03 17:37:27 | error: Error reading JSON file: ENOENT: no such file or directory, open 'D:\ersatzfiller\workdir\Weather\weather.json' | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at DerivedLogger.log (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:253:14)
    at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:95:19)
    at C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:118:16
    at async downloadimages (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:110:5)
    at async WEATHER (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:299:7)
    at async C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:37:3
2024-12-03 17:37:27 | error: weatherjsonObject is not defined | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14)
    at WEATHER (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:310:14)
    at async C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:37:3
2024-12-03 17:37:27 | error: Error encountered in Weather: ReferenceError: weatherjsonObject is not defined | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14)
    at C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:40:10
