### ISSUE TITLE
Still a weather issue since updating to 1.7.1

### ISSUE THREAD

**Issue by gjm19761** [liam8888999/ErsatzTV-Filler#234]
2024-12-03 17:37:26 | info: running weather function from run api
2024-12-03 17:37:26 | warn: Directory already exists, will not be created: D:\ersatzfiller\workdir\Weather
2024-12-03 17:37:26 | info: starting weather
2024-12-03 17:37:26 | success: Found the user selected theme file... loading...
2024-12-03 17:37:26 | debug: Current Theme json: [object Object]
2024-12-03 17:37:26 | debug: Hwaccell: no hwaccel
2024-12-03 17:37:26 | debug: Hwaccell_device: no hwacceldevice
2024-12-03 17:37:26 | debug: Weather video fade out start: 10
2024-12-03 17:37:26 | debug: Weather Audio Fade out start: 10
2024-12-03 17:37:26 | info: ass file path: D:\ersatzfiller\workdir\Weather\error.ass
2024-12-03 17:37:26 | info: ass location substituted: D\:/ersatzfiller/workdir/Weather/error.ass
2024-12-03 17:37:26 | info: Downloading weather images
2024-12-03 17:37:26 | info: Current City: Marlborough
2024-12-03 17:37:26 | info: Weatherdir: D:\ersatzfiller\workdir\Weather
2024-12-03 17:37:26 | success: D:\ersatzfiller\workdir\Weather\v1.png
2024-12-03 17:37:27 | success: D:\ersatzfiller\workdir\Weather\v2.png
2024-12-03 17:37:27 | success: D:\ersatzfiller\workdir\Weather\v3.png
2024-12-03 17:37:27 | error: Failed to download with status code 404 | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14)
    at ClientRequest.<anonymous> (C:\snapshot\ErsatzTV-Filler\server\utils\downloadimage.utils.js:27:16)
    at Object.onceWrapper (node:events:652:26)
    at ClientRequest.emit (node:events:537:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:642:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:505:22)
2024-12-03 17:37:27 | error: Failed to download with status code 404 | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async downloadimages (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:101:5)
    at async WEATHER (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:299:7)
    at async C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:37:3
2024-12-03 17:37:27 | error: Failed to download with status code 404 | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14)
    at ClientRequest.<anonymous> (C:\snapshot\ErsatzTV-Filler\server\utils\downloadimage.utils.js:27:16)
    at Object.onceWrapper (node:events:652:26)
    at ClientRequest.emit (node:events:537:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:642:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:505:22)
2024-12-03 17:37:27 | error: Failed to download with status code 404 | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async downloadimages (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:105:7)
    at async WEATHER (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:299:7)
    at async C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:37:3
2024-12-03 17:37:27 | error: Error reading JSON file: ENOENT: no such file or directory, open 'D:\ersatzfiller\workdir\Weather\weather.json' | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at DerivedLogger.log (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:253:14)
    at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:95:19)
    at C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:118:16
    at async downloadimages (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:110:5)
    at async WEATHER (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:299:7)
    at async C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:37:3
2024-12-03 17:37:27 | error: weatherjsonObject is not defined | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14)
    at WEATHER (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:310:14)
    at async C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:37:3
2024-12-03 17:37:27 | error: Error encountered in Weather: ReferenceError: weatherjsonObject is not defined | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14)
    at C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:40:10

**Comment by gjm19761** [comment]
i think its because im not in us? but in UK on weather for you my closest would be https://www.weatherforyou.com/clickcast/international/gb/boscombe+down.html

but ive tried boscombe down GB , boscombe down UK etc and it doesnt work. is it because its non searchable on there as its international?

**Comment by liam8888999** [comment]
Weatherforyou.net is us only. The alternative would be to use the booked.net option

**Comment by gjm19761** [comment]
ok how can we add in other sites?

**Comment by liam8888999** [comment]
@gjm19761 im not entirely sure what you mean but if you are asking how to add booked.net I would suggest having a look at the docs as a starting point

**Comment by gjm19761** [comment]
how do i get the filler to get weather from booked??

**Comment by liam8888999** [comment]
> how do i get the filler to get weather from booked??

https://liam8888999.github.io/ErsatzTV-Filler/configure/weather/#bookednet-widget-code should help. Let me know how I can make it better as it is a bit lacking. Basically though click on the link on the badge beside the space for the booked.net code to go, this will open booked.net, you then need to get a widget with your city etc. then click on get html and copy/paste that into the space provided

**Comment by gjm19761** [comment]
it worked... but only until today now getting this ;

2024-12-13 17:35:07 | success: D:\ersatztv-filler-windows-1.17.1\workdir\Weather\v1.png 
2024-12-13 17:35:09 | success: D:\ersatztv-filler-windows-1.17.1\workdir\Weather\v2.png 
2024-12-13 17:35:10 | success: D:\ersatztv-filler-windows-1.17.1\workdir\Weather\v3.png 
2024-12-13 17:35:10 | error: Failed to download: certificate has expired | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async downloadimages (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:101:5)
    at async WEATHER (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:299:7)
    at async C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:37:3
2024-12-13 17:35:10 | error: Error reading JSON file: Unexpected end of JSON input | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at DerivedLogger.log (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:253:14)
    at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:95:19)
    at C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:118:16
    at async downloadimages (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:110:5)
    at async WEATHER (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:299:7)
    at async C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:37:3
2024-12-13 17:35:10 | error: weatherjsonObject is not defined | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14)
    at WEATHER (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:310:14)
    at async C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:37:3
2024-12-13 17:35:10 | error: Error encountered in Weather: ReferenceError: weatherjsonObject is not defined | Error
    at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
    at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
    at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
    at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
    at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
    at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
    at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
    at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
    at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
    at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14)
    at C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:40:10

**Comment by gjm19761** [comment]
weird it sayaing c:\snapshot path as it not in that dir and that dir doesnt exist????

**Comment by liam8888999** [comment]
> it worked... but only until today now getting this ;
> 
> 
> 
> 2024-12-13 17:35:07 | success: D:\ersatztv-filler-windows-1.17.1\workdir\Weather\v1.png 
> 
> 2024-12-13 17:35:09 | success: D:\ersatztv-filler-windows-1.17.1\workdir\Weather\v2.png 
> 
> 2024-12-13 17:35:10 | success: D:\ersatztv-filler-windows-1.17.1\workdir\Weather\v3.png 
> 
> 2024-12-13 17:35:10 | error: Failed to download: certificate has expired | Error
> 
>     at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
> 
>     at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
> 
>     at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
> 
>     at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
> 
>     at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
> 
>     at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
> 
>     at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
> 
>     at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
> 
>     at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
> 
>     at C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14
> 
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
>     at async downloadimages (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:101:5)
> 
>     at async WEATHER (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:299:7)
> 
>     at async C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:37:3
> 
> 2024-12-13 17:35:10 | error: Error reading JSON file: Unexpected end of JSON input | Error
> 
>     at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
> 
>     at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
> 
>     at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
> 
>     at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
> 
>     at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
> 
>     at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
> 
>     at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
> 
>     at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
> 
>     at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
> 
>     at DerivedLogger.log (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:253:14)
> 
>     at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:95:19)
> 
>     at C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:118:16
> 
>     at async downloadimages (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:110:5)
> 
>     at async WEATHER (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:299:7)
> 
>     at async C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:37:3
> 
> 2024-12-13 17:35:10 | error: weatherjsonObject is not defined | Error
> 
>     at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
> 
>     at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
> 
>     at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
> 
>     at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
> 
>     at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
> 
>     at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
> 
>     at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
> 
>     at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
> 
>     at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
> 
>     at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14)
> 
>     at WEATHER (C:\snapshot\ErsatzTV-Filler\server\generators\weather.generator.js:310:14)
> 
>     at async C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:37:3
> 
> 2024-12-13 17:35:10 | error: Error encountered in Weather: ReferenceError: weatherjsonObject is not defined | Error
> 
>     at Printf.template (C:\snapshot\ErsatzTV-Filler\server\utils\logger.utils.js:50:76)
> 
>     at Printf.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\printf.js:11:26)
> 
>     at Format.transform (C:\snapshot\ErsatzTV-Filler\node_modules\logform\combine.js:20:24)
> 
>     at DerivedLogger._transform (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\logger.js:314:29)
> 
>     at DerivedLogger._read (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:166:10)
> 
>     at DerivedLogger._write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_transform.js:155:83)
> 
>     at doWrite (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:390:139)
> 
>     at writeOrBuffer (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:381:5)
> 
>     at DerivedLogger.write (C:\snapshot\ErsatzTV-Filler\node_modules\readable-stream\lib\_stream_writable.js:302:11)
> 
>     at DerivedLogger.error (C:\snapshot\ErsatzTV-Filler\node_modules\winston\lib\winston\create-logger.js:81:14)
> 
>     at C:\snapshot\ErsatzTV-Filler\server\routes\run.api.js:40:10
> 
> 

This appears to be more an issue with the site providing the information rather than the app itself from what I can see. I would recommend just giving it another try and see what happens

**Comment by liam8888999** [comment]
> weird it sayaing c:\snapshot path as it not in that dir and that dir doesnt exist????

This is an app internal location so it exists in the app but not on your local system

**Comment by gjm19761** [comment]
I have found the problem it's a weird one seems the weather.json was corrupted somehow, it did this on its own today somehow but I replaced it with the one from previous version and it's working with booked again.

**Comment by liam8888999** [comment]
That’s odd. In theory it should be redownloding the json every time it runs will look more into it I think On 14 Dec 2024, at 10:12 am, GJM ***@***.***> wrote:﻿
I have found the problem it's a weird one seems the weather.json was corrupted somehow, it did this on its own today somehow but I replaced it with the one from previous version and it's working with booked again.

**Comment by gjm19761** [comment]
it seems somehow looking at the last weather video when i noticed this issue that something happened tuesday and it stopped working as said it was weather.json that was truncated and there was also a weather2.json as well and remember the otherday it was saying weather already running, when it tried to do a weather request. so maybe a process failed somewhere and ersatzfiller thought it was already running and thats how files got corrupted?

**Comment by liam8888999** [comment]
I have previously noticed something similar, it’s noted down in the discord. My theory was that it has something to do with the network being saturated but I haven’t been able to narrow it down much at all as it seems kinda random On 15 Dec 2024, at 5:49 am, GJM ***@***.***> wrote:﻿
it seems somehow looking at the last weather video when i noticed this issue that something happened tuesday and it stopped working as said it was weather.json that was truncated and there was also a weather2.json as well and remember the otherday it was saying weather already running, when it tried to do a weather request. so maybe a process failed somewhere and ersatzfiller thought it was already running and thats how files got corrupted?

**Comment by liam8888999** [comment]
#242 have created a specific issue if you notice anything further @gjm19761
